### ISSUE TITLE
Water Quality

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#48]
Had a conversation with Laura Lorenzoni this morning, about the water quality product. They will produce a single indicator, only for the spotlight areas. Available from June 19 onward.

In the meantime, we will start talking to the science team to make sure they produce data we can pull in.

Sent this email with background to Laura.

> **Dashboard**
> A prototype for the agency dashboard is in development here: http://cv-eo.surge.sh/. This contains the general outline of the site. Expect this to change every couple of days as new features are released.
> 
> The dashboard will contain a couple of views:
> * the global products. This page shows data products with global coverage, focusing on map layers and timeseries data.
> * the spotlight areas provide more detailed
> * dataset pages, where your team can provide more background information about the data you produce.
> Some products will have data for both global and AOI views (eg. No2), others only for the spotlight areas (eg. Nightlights and Water Quality).
> 
> **API**
> All data is served through an API. This contains mostly:
> * map layers. Map data is served in Cloud Optimized GeoTIFF (COG) format. This format allows us to build a more dynamic experience for the user.
> * indicator data. This is mostly used at the AOI level to generate line-charts with timeseries data. A good format would be CSV, but we can support others.
> We can support your team to generate this data in the right format.
> 
> **Spotlight areas**
> The API contains an overview of the spotlight areas for all three agencies: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites
> You should feel free to use this endpoint and integrate in your data generation process.
> 
> **Next step**
> I'd love to have a conversation with your team. In particular about:
> * what you are planning to produce. Spatial and temporal resolution, output formats, frequency of updates, etc.
> * what kind of insights you're expecting to see, and we can communicate these clearly to your users
> Based on this conversation, we can come up with a more detailed plan about how our teams collaborate over the next couple of weeks.

**Comment by olafveerman** [comment]
@rwegener2 @abarciauskas-bgse The team has prepared anomaly maps in GeoTIFF format and will be sharing them. Looped you in on the email chain.

**Comment by abarciauskas-bgse** [comment]
Update from scrum Friday June 12:
* Brice (CCNY - CUNY) and Drew have been emailing about the data and it looks like Brice is using the https://github.com/NASA-IMPACT/covid-api/tree/master/guidelines to produce COGs and Drew is validating them
* We may just have to move Brice's data to S3 (I suggested we ask for them to share data over s3 / ftp / http if possible, and not google drive, but this might not always be an option)
* There could be more data coming next week that we should be prepared to spend some time supporting

**Comment by rwegener2** [comment]
Chlorophyll anomaly data for San Francisco has been uploaded to `s3://covid-eo-data/oc3_chla_anomaly`
Surface Particulate Matter anomaly data for San Francisco has been uploaded to `s3://covid-eo-data/spm_anomaly`

**Comment by drewbo** [comment]
@danielfdsilva 
- data up for San Francisco (`sf`), New York (`ny`) and North Adriatic (`nas`; not currently a site) from NASA:
  - Chlorophyll Anomaly, -100-100%, blue -> red  
  - requests look like: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Foc3_chla_anomaly%2Fanomaly-chl-{site_id}-{date}.tif&resampling_method=bilinear&bidx=1&rescale=-100%2C100&color_map=rdbu_r
  - dates available for `ny` and `nas`: 2020_01_01, 2020_01_08, 2020_01_15, 2020_01_22, 2020_01_29, 2020_02_05, 2020_02_12, 2020_02_19, 2020_02_26, 2020_03_04, 2020_03_11, 2020_03_18, 2020_03_25, 2020_04_01, 2020_04_08, 2020_04_15, 2020_04_22, 2020_04_29, 2020_05_06, 2020_05_13, 2020_05_20, 2020_05_27, 2020_06_03
  - dates available for `sf`: 2020_03_02, 2020_04_03, 2020_04_19, 2020_05_04, 2020_05_05, 2020_05_19, 2020_05_21, 2020_05_24
  - `sf` has an additional type of quality indicator `spm` (Suspended Particulate Matter) for the same dates; you can use the same url but replace `oc3_chla` and `chl` with `spm`
- data is also up for Tokyo (`tk`) from JAXA in a slightly different format (only difference is the rescaling parameter)
  - requests look like: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Foc3_chla_anomaly%2Fanomaly-chl-tk-{date}.tif&resampling_method=bilinear&bidx=1&color_map=rdbu_r
  - dates are slightly too numerous too list but apparently weekly starting 2017_12_27. So 2018_01_03 ... 2019_01_02...2020_01_01...2020_06_10
- JAXA has provided additional data for the North Adriatic which I haven't uploaded yet

**Comment by Schpidi** [comment]
@drewbo thanks, this works great.

two observations:
- the polygons from the sites endpoint don't fit this data for ny and tk
- tk has no transparency

![Screenshot from 2020-06-17 09-57-25](https://user-images.githubusercontent.com/482265/84871592-03d85380-b081-11ea-9727-0d5f18e43f9c.png)

![Screenshot from 2020-06-17 09-57-41](https://user-images.githubusercontent.com/482265/84871603-06d34400-b081-11ea-95bf-6fd35e6bbd0a.png)

**Comment by drewbo** [comment]
@Schpidi i'll touch base with both data providers to resolve. For the NY data, does the geometry issue hold across dates? It's possible that we fixed this and some old data is cached (we had a slight projection issue earlier)

**Comment by Schpidi** [comment]
@drewbo thanks for your reply. maybe I got the polygon from the wrong endpoint but I still see the mismatch. what would be the right url to retrieve the polygon?

**Comment by drewbo** [comment]
The polygon is correct, just that the files have data outside of the original bounds (likely because of the files from which they were derived)
